pipeline {
   agent any
   stages {
      stage('BUILD'){
         steps{
            sh 'mkdir dir4'
	    sh 'sleep 4'
         }
      }
      stage('TEST'){
         steps{
            sh 'mkdir dir5'
	    sh 'sleep 4'
         }
      }
      stage('DEPLOY'){
         steps{
            sh 'mkdir dir6'
            sh 'mkdir dir7'
         }
      }
   }
}
